// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package catalog

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p := messageKeyToIndex[key]
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"ru": &dictionary{index: ruIndex, data: ruData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"\u200d Found %d result(s)": 5,
	"☺️ Oh, you missed @toby3d birthday on November 4th!\nIf you like this bot, why not send him some birthday greetings and a little birthday gift? It is not yet too late to make him happy!": 14,
	"👋 Hi %s, I'm %s!\nThanks to me, you can collect almost any media content in Telegram without any limits, in any chat via inline mode.":                                                     0,
	"👍 Imported!": 2,
	"👍 Removed!":  4,
	"👍 Updated!":  3,
	"💡 Add any text and/or emoji(s) as an argument of this command to change its search properties.": 9,
	"💸 Make a donation":     15,
	"📥 Import %s set":       11,
	"📥 Import this photo":   7,
	"📥 Import this sticker": 10,
	"🔥 Remove %s set":       12,
	"🔥 Remove this photo":   8,
	"🔧 Let's hack!":         18,
	"🕺 HacktoberFest is here!\n\nIf you are a beginner or already an experienced golang-developer, now is a great time to help improve the quality of the code of this bot. Choose issue to your taste and offer your PR!": 17,
	"🤔 What to do with this?": 6,
	"🤖 Here is a list of commands that I understand, some of them [may] or (should) contain an argument:\n/start - start all over again\n/help [other command] - get a list of available commands or help and a demonstration of a specific command\n/add [query] - add media from reply to your collection [with custom search query]\n/edit (query) - change query to reply media\n/del - remove reply media from your collection": 1,
	"🤝 Use referral links": 16,
	"🥳 4 November? It's a @toby3d birthday!\nIf you like this bot, then why not send him a congratulation along with a small gift? This will make him incredibly happy!": 13,
}

var enIndex = []uint32{ // 20 elements
	0x00000000, 0x0000008e, 0x0000022b, 0x0000023a,
	0x00000248, 0x00000256, 0x00000270, 0x0000028b,
	0x000002a2, 0x000002b9, 0x0000031b, 0x00000334,
	0x0000034a, 0x00000360, 0x00000405, 0x000004c2,
	0x000004d7, 0x000004ef, 0x000005c5, 0x000005d6,
} // Size: 104 bytes

const enData string = "" + // Size: 1494 bytes
	"\x02👋 Hi %[1]s, I'm %[2]s!\x0aThanks to me, you can collect almost any m" +
	"edia content in Telegram without any limits, in any chat via inline mode" +
	".\x02🤖 Here is a list of commands that I understand, some of them [may] " +
	"or (should) contain an argument:\x0a/start - start all over again\x0a/he" +
	"lp [other command] - get a list of available commands or help and a demo" +
	"nstration of a specific command\x0a/add [query] - add media from reply t" +
	"o your collection [with custom search query]\x0a/edit (query) - change q" +
	"uery to reply media\x0a/del - remove reply media from your collection" +
	"\x02👍 Imported!\x02👍 Updated!\x02👍 Removed!\x02\u200d Found %[1]d result" +
	"(s)\x02🤔 What to do with this?\x02📥 Import this photo\x02🔥 Remove this p" +
	"hoto\x02💡 Add any text and/or emoji(s) as an argument of this command to" +
	" change its search properties.\x02📥 Import this sticker\x02📥 Import %[1]" +
	"s set\x02🔥 Remove %[1]s set\x02🥳 4 November? It's a @toby3d birthday!" +
	"\x0aIf you like this bot, then why not send him a congratulation along w" +
	"ith a small gift? This will make him incredibly happy!\x02☺️ Oh, you mis" +
	"sed @toby3d birthday on November 4th!\x0aIf you like this bot, why not s" +
	"end him some birthday greetings and a little birthday gift? It is not ye" +
	"t too late to make him happy!\x02💸 Make a donation\x02🤝 Use referral lin" +
	"ks\x02🕺 HacktoberFest is here!\x0a\x0aIf you are a beginner or already a" +
	"n experienced golang-developer, now is a great time to help improve the " +
	"quality of the code of this bot. Choose issue to your taste and offer yo" +
	"ur PR!\x02🔧 Let's hack!"

var ruIndex = []uint32{ // 20 elements
	0x00000000, 0x00000106, 0x000003b4, 0x000003d5,
	0x000003ee, 0x00000403, 0x00000433, 0x00000459,
	0x00000482, 0x0000049d, 0x0000055c, 0x00000589,
	0x000005af, 0x000005c7, 0x000006fc, 0x00000855,
	0x00000884, 0x000008d2, 0x00000a27, 0x00000a38,
} // Size: 104 bytes

const ruData string = "" + // Size: 2616 bytes
	"\x02👋 Привет %[1]s, я %[2]s!\x0aБлагодаря мне, ты можешь коллекционирова" +
	"ть в inline-режиме практически любой медиа-контент Telegram без огранич" +
	"ений, в любом чате.\x02🤖 Вот список которые я понимаю, некоторые из них" +
	" [могут] или (должны) содержать аргументы:\x0a/start - начать всё заново" +
	"\x0a/help [другая команда] - получить список всех доступных команд или с" +
	"правку о конкретной команде\x0a/add [текст] - добавить медиа из ответа " +
	"в коллекцию [с указанным поисковым тегом]\x0a/edit (текст) - изменить п" +
	"оисковый тег медиа из ответа\x0a/del - удалить медиа из ответа из колле" +
	"кции\x02👍 Импортировано!\x02👍 Обновлено!\x02👍 Удалено!\x02\u200d Найден" +
	"о %[1]d результатов\x02🤔 Что с этим делать?\x02📥 Импортировать фото\x02" +
	"🔥 Убрать фото\x02💡 Добавь любой текст и/или эмодзи в качестве аргумен" +
	"та этой команды чтобы изменить поисковые свойства.\x02📥 Импортировать с" +
	"тикер\x02📥 Импортировать %[1]s\x02🔥 Убрать %[1]s\x02🥳 4-е Ноября? Это д" +
	"ень рождения @toby3d!\x0aЕсли тебе нравится этот бот, то почему бы не о" +
	"тправить ему поздравления вместе с небольшим подарком? Это несказанно е" +
	"го осчастливит!\x02☺️ Ой, ты пропустил день рождения @toby3d 4-го Ноябр" +
	"я!\x0aЕсли тебе нравится этот бот, то почему бы не отправить ему поздра" +
	"вления вместе с небольшим подарком? Ещё не слишком поздно его порадоват" +
	"ь!\x02💸 Сделать пожертвование\x02🤝 Воспользоваться реферальными ссылкам" +
	"и\x02🕺 Хактоберфест уже здесь!\x0a\x0aЕсли ты начинающий или уже опытны" +
	"й golang-разработчик, то сейчас хорошее время помочь улучшить качество " +
	"кода этого бота. Выбери issue на твой вкус и предложи свой PR!\x02🔧 Let" +
	"'s hack!"

	// Total table size 4318 bytes (4KiB); checksum: 12554C98
