telegram:
  token: 123456789:ABCd1efGhjKLM23O4pqR5stuvwx678yz90
  webhook:
    set: https://toby3d.github.io
    listen: /bot
    serve: 0.0.0.0:2368
    allowed_updates:
      - inline_query
      - message
      - channel_post
      - callback_query
  long_poll:
    limit: 100
    offset: 0
    timeout: 1
    allowed_updates:
      - inline_query
      - message
      - channel_post
      - callback_query
database:
  filepath: ./development.db