// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package main

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p := messageKeyToIndex[key]
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"/%s - adds stickers one by one to your collection\n/%s - adds the entire set to your\n/%s at once - removes the sticker from your set one by one\n/%s - deletes the sticker set from your set\n/%s - removes all stickers from your set\n/%s - undoes the current operation\n\nTo view and send stickers from your set, simply type `@%s` (and space) in any chat.": 32,
	"All of the *%s* stickers are already in your collection.":                                                                                                                                                    11,
	"Hello, I'm @%s!\nI can create your personal set of stickers from other sets.\nWithout restrictions and installation. In any chat. Is free.":                                                                  35,
	"I have no idea what to do with this sticker.\nPlease use /%s, /%s, /%s or /%s first.":                                                                                                                        16,
	"It seems you're trying to add your own sticker. Use the /%s command for this.":                                                                                                                               9,
	"No stickers found for %s":                                                                                                                                                                                    36,
	"Nothing to cancel.":                                                                                                                                                                                          27,
	"Nothing to delete, the set is already empty.":                                                                                                                                                                28,
	"Probably this set is already removed from yours.":                                                                                                                                                            14,
	"Probably this sticker is already removed from your set.":                                                                                                                                                     15,
	"Send a sticker from your set to remove all of its set.":                                                                                                                                                      30,
	"Send a sticker from your set to remove it.":                                                                                                                                                                  29,
	"Send stickers from any other sets to add them one by one.":                                                                                                                                                   20,
	"Send stickers from any other sets to completely add their sets to your.":                                                                                                                                     21,
	"The set *%s* was successfully added to yours!":                                                                                                                                                               10,
	"The set *%s* was successfully removed from your collection!":                                                                                                                                                 13,
	"The sticker has been successfully removed from your set!":                                                                                                                                                    12,
	"The sticker was successfully added to your set!":                                                                                                                                                             7,
	"There is nothing to discard, the set is already empty.":                                                                                                                                                      33,
	"This button will help you quickly call your kit to select the sticker you want.":                                                                                                                             31,
	"This operation will remove *all* stickers from your set and *this can not be undone*.\n\nWrite `%s` to confirm my intention to zero my brain (oh god why).\nIf you use /%s to cancel the current operation.": 34,
	"This sticker is already in your collection.":                            8,
	"Wrong phrase for reset. The action was canceled.":                       18,
	"Yes, I am absolutely sure.":                                             17,
	"You canceled the process of adding new sets to yours.":                  23,
	"You canceled the process of adding new stickers to your collection.":    22,
	"You canceled the process of removing sets from your collection.":        25,
	"You canceled the process of removing the sticker from your collection.": 24,
	"You canceled the process of resetting your collection.":                 26,
	"Your set has successfully reseted!":                                     19,
	"add a sticker":                                                          1,
	"add set":                                                                2,
	"cancel":                                                                 0,
	"delete set":                                                             4,
	"remove sticker":                                                         3,
	"reset set":                                                              5,
	"select sticker":                                                         6,
}

var enIndex = []uint32{ // 38 elements
	// Entry 0 - 1F
	0x00000000, 0x00000007, 0x00000015, 0x0000001d,
	0x0000002c, 0x00000037, 0x00000041, 0x00000050,
	0x00000080, 0x000000ac, 0x000000fd, 0x0000012e,
	0x0000016a, 0x000001a3, 0x000001e2, 0x00000213,
	0x0000024b, 0x000002ab, 0x000002c6, 0x000002f7,
	0x0000031a, 0x00000354, 0x0000039c, 0x000003e0,
	0x00000416, 0x0000045d, 0x0000049d, 0x000004d4,
	0x000004e7, 0x00000514, 0x0000053f, 0x00000576,
	// Entry 20 - 3F
	0x000005c6, 0x00000737, 0x0000076e, 0x0000083d,
	0x000008c9, 0x000008e5,
} // Size: 176 bytes

const enData string = "" + // Size: 2277 bytes
	"\x02cancel\x02add a sticker\x02add set\x02remove sticker\x02delete set" +
	"\x02reset set\x02select sticker\x02The sticker was successfully added to" +
	" your set!\x02This sticker is already in your collection.\x02It seems yo" +
	"u're trying to add your own sticker. Use the /%[1]s command for this." +
	"\x02The set *%[1]s* was successfully added to yours!\x02All of the *%[1]" +
	"s* stickers are already in your collection.\x02The sticker has been succ" +
	"essfully removed from your set!\x02The set *%[1]s* was successfully remo" +
	"ved from your collection!\x02Probably this set is already removed from y" +
	"ours.\x02Probably this sticker is already removed from your set.\x02I ha" +
	"ve no idea what to do with this sticker.\x0aPlease use /%[1]s, /%[2]s, /" +
	"%[3]s or /%[4]s first.\x02Yes, I am absolutely sure.\x02Wrong phrase for" +
	" reset. The action was canceled.\x02Your set has successfully reseted!" +
	"\x02Send stickers from any other sets to add them one by one.\x02Send st" +
	"ickers from any other sets to completely add their sets to your.\x02You " +
	"canceled the process of adding new stickers to your collection.\x02You c" +
	"anceled the process of adding new sets to yours.\x02You canceled the pro" +
	"cess of removing the sticker from your collection.\x02You canceled the p" +
	"rocess of removing sets from your collection.\x02You canceled the proces" +
	"s of resetting your collection.\x02Nothing to cancel.\x02Nothing to dele" +
	"te, the set is already empty.\x02Send a sticker from your set to remove " +
	"it.\x02Send a sticker from your set to remove all of its set.\x02This bu" +
	"tton will help you quickly call your kit to select the sticker you want." +
	"\x02/%[1]s - adds stickers one by one to your collection\x0a/%[2]s - add" +
	"s the entire set to your\x0a/%[3]s at once - removes the sticker from yo" +
	"ur set one by one\x0a/%[4]s - deletes the sticker set from your set\x0a/" +
	"%[5]s - removes all stickers from your set\x0a/%[6]s - undoes the curren" +
	"t operation\x0a\x0aTo view and send stickers from your set, simply type " +
	"`@%[7]s` (and space) in any chat.\x02There is nothing to discard, the se" +
	"t is already empty.\x02This operation will remove *all* stickers from yo" +
	"ur set and *this can not be undone*.\x0a\x0aWrite `%[1]s` to confirm my " +
	"intention to zero my brain (oh god why).\x0aIf you use /%[2]s to cancel " +
	"the current operation.\x02Hello, I'm @%[1]s!\x0aI can create your person" +
	"al set of stickers from other sets.\x0aWithout restrictions and installa" +
	"tion. In any chat. Is free.\x02No stickers found for %[1]s"

	// Total table size 2453 bytes (2KiB); checksum: 18B7B4EE
