// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package main

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p := messageKeyToIndex[key]
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"ru": &dictionary{index: ruIndex, data: ruData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"callback__text_add-set":        2,
	"callback__text_add-single":     0,
	"callback__text_language":       10,
	"callback__text_language-same":  8,
	"callback__text_remove-set":     6,
	"callback__text_remove-single":  4,
	"help__text":                    14,
	"inline__found_switch-text":     12,
	"inline__not-found_switch-text": 11,
	"settings-command__text":        9,
	"start__text":                   13,
	"sticker__button_add-set":       7,
	"sticker__button_add-single":    5,
	"sticker__button_remove-set":    3,
	"sticker__button_remove-single": 1,
	"sticker__text":                 16,
	"unknown-command__text":         15,
}

var enIndex = []uint32{ // 18 elements
	0x00000000, 0x0000002f, 0x00000043, 0x00000065,
	0x00000075, 0x00000094, 0x000000a8, 0x000000c9,
	0x000000d9, 0x00000100, 0x00000110, 0x00000120,
	0x00000145, 0x0000016f, 0x00000186, 0x0000018b,
	0x000001ad, 0x000001d0,
} // Size: 96 bytes

const enData string = "" + // Size: 464 bytes
	"\x02📲 Sticker from %[1]v set has been imported!\x02🔥 Remove sticker\x02📲" +
	" Set %[1]v has been imported!\x02🔥 Remove set\x02🔥 Sticker has been remo" +
	"ved!\x02📙 Import sticker\x02🔥 Set %[1]v has been removed!\x02📚 Import se" +
	"t\x02🐞 This language is already selected\x02⚙️ Settings\x02👋🏻 Hello!\x02" +
	"🤷🏻\u200d♂️ Stickers not found\x02🕵🏻️\u200d♂️ Found %[1]v stickers\x02" +
	"👋🏻 Hello, %[1]v!\x02Helo\x02🤷🏻\u200d♂️ Unknown command\x02🤔 What to d" +
	"o with this sticker?"

var ruIndex = []uint32{ // 18 elements
	0x00000000, 0x00000044, 0x00000063, 0x00000093,
	0x000000b0, 0x000000cf, 0x000000fc, 0x0000011f,
	0x0000014a, 0x00000175, 0x0000018f, 0x000001a6,
	0x000001d9, 0x00000214, 0x00000232, 0x0000023f,
	0x00000277, 0x000002ae,
} // Size: 96 bytes

const ruData string = "" + // Size: 686 bytes
	"\x02📲 Стикер из набора %[1]v импортирован!\x02🔥 Убрать стикер\x02📲 Набор" +
	" %[1]v импортирован!\x02🔥 Убрать набор\x02🔥 Стикер удалён\x02📙 Импортиро" +
	"вать стикер\x02🔥 Набор %[1]v удалён\x02📚 Импортировать набор\x02🐞 Этот " +
	"язык уже выбран\x02⚙️ Настройки\x02👋🏻 Привет!\x02🤷🏻\u200d♂️ Ничего не н" +
	"айдено\x02🕵🏻️\u200d♂️ Найдено %[1]v стикеров\x02👋🏻 Привет, %[1]v!\x02По" +
	"мощь\x02🤷🏻\u200d♂️ Неизвестная команда\x02🤔 Что делать с этим стикером?"

	// Total table size 1342 bytes (1KiB); checksum: D59659D7
